#include "keys.h"

const char *key_to_str(unsigned char key)
{
	switch (key) {
	case K_BACK: return "BACK";
	case K_TAB: return "TAB";
	case K_CLEAR: return "CLEAR";
	case K_RETURN: return "RETURN";
	case K_SHIFT: return "SHIFT";
	case K_CONTROL: return "CONTROL";
	case K_MENU: return "MENU";
	case K_PAUSE: return "PAUSE";
	case K_CAPITAL: return "CAPITAL";
	case K_ESCAPE: return "ESCAPE";
	case K_SPACE: return "SPACE";
	case K_PRIOR: return "PRIOR";
	case K_NEXT: return "NEXT";
	case K_END: return "END";
	case K_HOME: return "HOME";
	case K_LEFT: return "LEFT";
	case K_UP: return "UP";
	case K_RIGHT: return "RIGHT";
	case K_DOWN: return "DOWN";
	case K_SELECT: return "SELECT";
	case K_PRINT: return "PRINT";
	case K_EXECUTE: return "EXECUTE";
	case K_SNAPSHOT: return "SNAPSHOT";
	case K_INSERT: return "INSERT";
	case K_DELETE: return "DELETE";
	case K_HELP: return "HELP";
	case K_A: return "A";
	case K_B: return "B";
	case K_C: return "C";
	case K_D: return "D";
	case K_E: return "E";
	case K_F: return "F";
	case K_G: return "G";
	case K_H: return "H";
	case K_I: return "I";
	case K_J: return "J";
	case K_K: return "K";
	case K_L: return "L";
	case K_M: return "M";
	case K_N: return "N";
	case K_O: return "O";
	case K_P: return "P";
	case K_Q: return "Q";
	case K_R: return "R";
	case K_S: return "S";
	case K_T: return "T";
	case K_U: return "U";
	case K_V: return "V";
	case K_W: return "W";
	case K_X: return "X";
	case K_Y: return "Y";
	case K_Z: return "Z";
	case K_SLEEP: return "SLEEP";
	case K_NUMPAD0: return "NUMPAD0";
	case K_NUMPAD1: return "NUMPAD1";
	case K_NUMPAD2: return "NUMPAD2";
	case K_NUMPAD3: return "NUMPAD3";
	case K_NUMPAD4: return "NUMPAD4";
	case K_NUMPAD5: return "NUMPAD5";
	case K_NUMPAD6: return "NUMPAD6";
	case K_NUMPAD7: return "NUMPAD7";
	case K_NUMPAD8: return "NUMPAD8";
	case K_NUMPAD9: return "NUMPAD9";
	case K_MULTIPLY: return "MULTIPLY";
	case K_ADD: return "ADD";
	case K_SEPARATOR: return "SEPARATOR";
	case K_SUBTRACT: return "SUBTRACT";
	case K_DECIMAL: return "DECIMAL";
	case K_DIVIDE: return "DIVIDE";
	case K_F1: return "F1";
	case K_F2: return "F2";
	case K_F3: return "F3";
	case K_F4: return "F4";
	case K_F5: return "F5";
	case K_F6: return "F6";
	case K_F7: return "F7";
	case K_F8: return "F8";
	case K_F9: return "F9";
	case K_F10: return "F10";
	case K_F11: return "F11";
	case K_F12: return "F12";
	case K_F13: return "F13";
	case K_F14: return "F14";
	case K_F15: return "F15";
	case K_F16: return "F16";
	case K_F17: return "F17";
	case K_F18: return "F18";
	case K_F19: return "F19";
	case K_F20: return "F20";
	case K_F21: return "F21";
	case K_F22: return "F22";
	case K_F23: return "F23";
	case K_F24: return "F24";
	case K_BACKQUOTE: return "BACKQUOTE";
	case K_1: return "1";
	case K_2: return "2";
	case K_3: return "3";
	case K_4: return "4";
	case K_5: return "5";
	case K_6: return "6";
	case K_7: return "7";
	case K_8: return "8";
	case K_9: return "9";
	case K_0: return "0";
	case K_MINUS: return "MINUS";
	case K_EQUAL: return "EQUAL";
	case K_BACKSPACE: return "BACKSPACE";
	case K_CAPSLOCK: return "CAPSLOCK";
	case K_ALT: return "ALT";
	case K_ALTGR: return "ALTGR";
	case K_BRACKETLEFT: return "BRACKETLEFT";
	case K_BACKSLASH: return "BACKSLASH";
	case K_BRACKETRIGHT: return "BRACKETRIGHT";
	case K_SEMICOLON: return "SEMICOLON";
	case K_QUOTE: return "QUOTE";
	case K_COMMA: return "COMMA";
	case K_PUNT: return "PUNT";
	case K_QUESTION: return "QUESTION";
	case K_LSHIFT: return "LSHIFT";
	case K_RSHIFT: return "RSHIFT";
	case K_LCONTROL: return "LCONTROL";
	case K_RCONTROL: return "RCONTROL";
	case K_LOS: return "LOS";
	case K_ROS: return "ROS";
	case K_CONTEXTMENU: return "CONTEXTMENU";
	case K_ARROWUP: return "ARROWUP";
	case K_ARROWLEFT: return "ARROWLEFT";
	case K_ARROWRIGHT: return "ARROWRIGHT";
	case K_ARROWDOWN: return "ARROWDOWN ";
	case K_PAGEUP: return "PAGEUP";
	case K_PAGEDOWN: return "PAGEDOWN";
	case K_SCROLLLOCK: return "SCROLLLOCK";
	case K_NUMLOCK: return "NUMLOCK";
	case K_SLASH: return "SLASH";
	case K_UNDERSCORE: return "UNDERSCORE";
	case K_NUMPADDEL: return "NUMPADDEL";
	case K_NUMPADRETURN: return "NUMPADRETURN";
	default: return "UNKNWON";
	}
}

const char *mouse_to_str(unsigned char mouse)
{
	switch (mouse) {
	case K_MOUSEL: return "MOUSEL";
	case K_MOUSEM: return "MOUSEM";
	case K_MOUSER: return "MOUSER";
	case K_MOUSEMUP: return "MOUSEMUP";
	case K_MOUSEMDOWN: return "MOUSEMDOWN";
	case K_MOUSES0: return "MOUSES0";
	case K_MOUSES1: return "MOUSES1";
	default: return "UNKNOWN";
	}
}
